# This is a basic workflow to help you get started with Actions

name: Windows Build 7.0

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      source_repository:
        description: 'Source repository to use'
        required: true
        default: 'krzysfr/foundationdb'
      source_branch:
        description: 'Branch in source repository'
        required: true
        default: windows-docker-build-7.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Pull FoundationDB source code
        with:
          repository: ${{ github.event.inputs.source_repository }}
          ref: ${{ github.event.inputs.source_branch }}
          
      # Runs a single command using the runners shell
      - name: Run Build
        shell: pwsh
        run: |
          cd .\build
          .\build.ps1 -BuildDir ..\output
