# This is a basic workflow to help you get started with Actions

name: Windows CI Build

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      source_repository:
        description: 'Source repository to use'
        required: true
        default: 'apple/foundationdb'
      source_branch:
        description: 'Branch in source repository'
        required: true
        default: master
      build_repository:
        description: 'Build repository to use'
        required: true
        default: 'foundationdb/fdb-build-support'
      build_branch:
        description: 'Branch in build repository'
        required: true
        default: main
      cpus:
        description: 'Number of cpu cores'
        default: '16'
      memory:
        description: 'Total memory size (in bytes)'
        default: '32000000000'
      buildConfig:
        description: 'Build Configuration'
        default: 'Release'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, windows, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Cleanup workspace to discard any artifact from previous runs
      - name: Cleanup workspace
        shell: powershell
        run: |
          Remove-Item -Recurse -Force .\artifacts -ErrorAction Ignore
      
      # Checkout the source repository
      - uses: actions/checkout@v2
        name: Pull FoundationDB source code
        with:
          repository: ${{ github.event.inputs.source_repository }}
          ref: ${{ github.event.inputs.source_branch }}
          path: source

      # Checkout the build repository
      - uses: actions/checkout@v2
        name: Pull FoundationDB build support code
        with:
          repository: ${{ github.event.inputs.build_repository }}
          ref: ${{ github.event.inputs.build_branch }}
          path: build
          
      # Runs a single command using the runners shell
      - name: Run Build
        shell: powershell
        run: |
          md .\artifacts
          cd .\build\docker\windows\devel
          .\build.ps1 -SourceDir ..\..\..\..\source -BuildDir ..\..\..\..\artifacts -Cpus ${{ github.event.inputs.cpus }} -Memory ${{ github.event.inputs.memory }} -BuildConfig ${{ github.event.inputs.buildConfig }}
