name: Windows Nightlies Builds

on:
  workflow_dispatch:
  schedule:
  - cron: '0 3 * * *'
    
jobs:  
  build:
    runs-on: [self-hosted, windows, x64, nightlies]

    steps:    
      # Cleanup workspace to discard any artifact from previous runs
      - name: Cleanup workspace
        shell: powershell
        run: |
          Remove-Item -Recurse -Force .\build -ErrorAction Ignore
     
     # Checkout the build repository
      - uses: actions/checkout@v2
        name: Pull the build script
        with:
          repository: Doxense/foundationdb-windows-build
          ref: main
          path: ${{ github.workspace }}/build/sources
     
      # Runs a single command using the runners shell
      - name: Run Build
        continue-on-error: true
        shell: cmd
        run : |
          cd .\build
          powershell.exe -File .\sources\fdb_nightlies.ps1 -RunId ${{github.run_id}} -SlackPath "${{ secrets.SLACK_PATH }}"
        
      # Publish build logs
      - uses: actions/upload-artifact@v2
        name: Publish Artifacts
        with:
          name: build_logs
          path: ${{ github.workspace }}/build/build_logs
