# This is a basic workflow to help you get started with Actions

name: Generate Windows Docker Build Image

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
      source_repository:
        description: 'Source repository to use'
        required: true
        default: 'foundationdb/fdb-build-support'
      source_branch:
        description: 'Branch in source repository'
        required: true
        default: master
      target_image:
        description: 'Target image name'
        required: true
        default: doxense/foundationdb-windows-build
      target_registry:
        description: 'Target docker registry'
        required: true
        default: docker.io
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the foundationdb repository code
      - uses: actions/checkout@v2
        name: Pull FoundationDB source code
        with:
          repository: ${{ github.event.inputs.source_repository }}
          ref: ${{ github.event.inputs.source_branch }}
       
      # Build the docker build image
      - uses: mr-smithers-excellent/docker-build-push@v5.3
        name: Build & Push Docker image
        with:
          image: ${{ github.event.inputs.target_image }}
          registry: ${{ github.event.inputs.target_registry }}
          tags: ${{ github.event.inputs.tag }}, latest
          dockerfile: ./docker/windows/build/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
