name: Test Fork

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: [self-hosted, windows, x64, nightlies]

    steps:
      - id: publish_output
        run: echo "::set-output name=matrix::$(powershell -File D:\source\test\publish.ps1)"
      - id: show_result
        run: echo  ${{ steps.publish_output.outputs.matrix }}

    outputs:
      matrix: ${{ steps.publish_output.outputs.matrix }}
      
  consume:
    needs: publish
    runs-on: [self-hosted, windows, x64, nightlies]
    strategy:
      matrix:
        package: ${{ fromJson(needs.publish.outputs.matrix) }}
    steps:
      - id: use_output
        run: powershell -File D:\source\test\consume.ps1 -Id "$GITHUB_JOB"
